on:
  workflow_call:

jobs:
  build:
    name: Build Prism.Maui
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: NuGet Restore
        run: dotnet restore build.slnf

      - name: Build Packages
        run: dotnet build build.slnf -c Release

      - name: Run Tests
        run: dotnet test build.slnf -c Release --no-build

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Prism.Maui Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: Artifacts/


