name: Build Prism.Maui

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.vscode/**'
      - '.github/*'
      - '.git*'
      - '.editorconfig'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.vscode/**'
      - '.github/*'
      - '.git*'
      - '.editorconfig'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build Prism.Maui
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: NuGet Restore
        run: dotnet restore build.slnf

      - name: Build Packages
        run: dotnet build build.slnf -c Release

      - name: Run Tests
        run: dotnet test build.slnf -c Release --no-build

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Prism.Maui Tests
          path: ./TestResults/*.trx
          reporter: dotnet-trx

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

  sign-packages:
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      # Known issue https://github.com/novotnyllc/NuGetKeyVaultSignTool/issues/95
      - name: Sign NuGet Packages
        working-directory: Artifacts/
        run: |
          dotnet tool install --global NuGetKeyVaultSignTool
          NuGetKeyVaultSignTool sign *.nupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 '${{ secrets.CodeSignTimestampUrl }}' `
            --timestamp-digest sha256 `
            --azure-key-vault-url '${{ secrets.CodeSignKeyVault }}' `
            --azure-key-vault-client-id '${{ secrets.CodeSignClientId }}' `
            --azure-key-vault-tenant-id '${{ secrets.CodeSignTenantId }}' `
            --azure-key-vault-client-secret '${{ secrets.CodeSignClientSecret }}' `
            --azure-key-vault-certificate '${{ secrets.CodeSignCertificate }}'
          NuGetKeyVaultSignTool sign *.snupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 '${{ secrets.CodeSignTimestampUrl }}' `
            --timestamp-digest sha256 `
            --azure-key-vault-url '${{ secrets.CodeSignKeyVault }}' `
            --azure-key-vault-client-id '${{ secrets.CodeSignClientId }}' `
            --azure-key-vault-tenant-id '${{ secrets.CodeSignTenantId }}' `
            --azure-key-vault-client-secret '${{ secrets.CodeSignClientSecret }}' `
            --azure-key-vault-certificate '${{ secrets.CodeSignCertificate }}'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Signed
          path: Artifacts/

  deploy-internal:
    uses: ./.github/workflows/deploy.yml
    needs: sign-packages
    if: ${{ github.event_name != 'pull_request' }}
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    uses: ./.github/workflows/deploy.yml
    needs: sign-packages
    if: ${{ github.event_name != 'pull_request' }}
    with:
      name: Deploy Sponsor Connect
    secrets:
      feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
      apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}
