on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: Deploy
      artifactName:
        required: false
        type: string
        default: NuGet
      artifactPath:
        required: false
        type: string
        default: Artifacts/
      feedUrl:
        required: true
        type: string
      apiKey:
        required: true
        type: string

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}

      - name: NuGet Publish (In-House)
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: '${{ inputs.artifactPath }}*.nupkg'
            feedUrl: ${{ inputs.feedUrl }}
            apiKey: ${{ inputs.apiKey }}