on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: Deploy
      feedUrl:
        required: true
        type: string
      apiKey:
        required: true
        type: string

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      - name: ${{ inputs.name }}
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ inputs.feedUrl }}
            apiKey: ${{ inputs.apiKey }}