on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: Deploy
    secrets:
      feedUrl:
        required: true
      apiKey:
        required: true

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: NuGet
          path: Artifacts/

      # Known issue https://github.com/novotnyllc/NuGetKeyVaultSignTool/issues/95
      - name: Sign NuGet Packages
        run: |
          NuGetKeyVaultSignTool sign ./Artifacts/*.nupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 ${{ secrets.CodeSignTimestampUrl }} `
            --timestamp-digest sha256 `
            --azure-key-vault-url ${{ secrets.CodeSignKeyVault }} `
            --azure-key-vault-client-id ${{ secrets.CodeSignClientId }} `
            --azure-key-vault-tenant-id ${{ secrets.CodeSignTenantId }} `
            --azure-key-vault-client-secret ${{ secrets.CodeSignClientSecret }} `
            --azure-key-vault-certificate ${{ secrets.CodeSignCertificate }}
          NuGetKeyVaultSignTool sign ./Artifacts/*.snupkg `
            --file-digest sha256 `
            --timestamp-rfc3161 ${{ secrets.CodeSignTimestampUrl }} `
            --timestamp-digest sha256 `
            --azure-key-vault-url ${{ secrets.CodeSignKeyVault }} `
            --azure-key-vault-client-id ${{ secrets.CodeSignClientId }} `
            --azure-key-vault-tenant-id ${{ secrets.CodeSignTenantId }} `
            --azure-key-vault-client-secret ${{ secrets.CodeSignClientSecret }} `
            --azure-key-vault-certificate ${{ secrets.CodeSignCertificate }}

      - name: ${{ inputs.name }}
        uses: dansiegel/publish-nuget@v1.01
        with:
            filename: 'Artifacts/*.nupkg'
            feedUrl: ${{ secrets.feedUrl }}
            apiKey: ${{ secrets.apiKey }}