name: Start NuGet Release

on:
  workflow_dispatch:

jobs:
  build-packages:
    uses: ./.github/workflows/build-packages.yml
    secrets: inherit

  sign-packages:
    uses: ./.github/workflows/sign.yml
    needs: build-packages
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [sign-packages]
    name: Release
    permissions:
      contents: write
    outputs:
      version-name: ${{ steps.process-version.outputs.version-name }}
      release-display-name: ${{ steps.process-version.outputs.release-display-name }}
      is-preview: ${{ steps.process-version.outputs.is-preview }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: Signed
        path: Artifacts/

    - run: perl ../build/process-version.pl Prism.Maui
      shell: bash
      id: process-version
      name: Process Version
      working-directory: Artifacts/

    - uses: ncipollo/release-action@main
      name: Create Release
      with:
        artifacts: "Artifacts/*.nupkg,Artifacts/*.snupkg"
        artifactErrorsFailBuild: true
        draft: true
        generateReleaseNotes: true
        name: ${{ steps.process-version.outputs.release-display-name }}
        prerelease: ${{ steps.process-version.outputs.is-preview }}
        tag: ${{ steps.process-version.outputs.version-name }}